alias b='bundle exec'
alias hrc='heroku run --size=performance-m rails console -a teepublic'
alias hrcs='heroku run --size=performance-l rails console -a teepublic-staging'
alias dcu='docker compose up'
alias dcp='docker compose -f docker-compose.profiles.yml up -d'
alias dcpt='docker compose -f docker-compose.profiles.yml --profile test up -d'
alias dcd='docker compose down'
alias clear_test_db='b rake db:drop RAILS_ENV=test && b rake db:create RAILS_ENV=test && b rake db:schema:load RAILS_ENV=test'
alias git_soft_reset='git reset --soft HEAD^'
